class Config():
    DEBUG = False
    SQLITE_DB_DIR = None
    SQLALCHEMY_DATABASE_URI = None
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SECRET_KEY = None
    SECURITY_PASSWORD_HASH = None
    SECURITY_PASSWORD_SALT = None
    SECURITY_REGISTRABLE = None
    SECURITY_SEND_REGISTER_EMAIL = None
    SECURITY_UNAUTHORIZED_VIEW = None

